### ISSUE TITLE
[WCLIENT 1.0] java.io.FileNotFoundException: /home/projecttl/.minecraft/waypoints (Is a directory) [AUTO GENERATED]

### ISSUE THREAD

**Issue by WinChoReportingSystem** [WintChoco/WinchoClient#22]
keyPressed event handler
```
Description: java.io.FileNotFoundException: /home/projecttl/.minecraft/waypoints (Is a directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at net.minecraft.class_746.handler$zzb000$sendChatMessage(class_746.java:1292)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:376)
	at net.minecraft.class_437.method_25427(class_437.java:369)
	at net.optifine.gui.GuiChatOF.method_25427(GuiChatOF.java:41)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:374)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:703)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22676(class_309.java:702)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:159)
	at net.minecraft.class_1041.method_15998(class_1041.java:454)
	at net.minecraft.class_310.method_1523(class_310.java:1139)
	at net.minecraft.class_310.method_1514(class_310.java:3667)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

```

```
-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (amd64) version 5.12.12-300.fc34.x86_64
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 909178848 bytes (867 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: GP106 [GeForce GTX 1060 3GB]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 14159.60
	Virtual memory used (MB): 9077.21
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 305.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.84, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
```

**Comment by WinChoReportingSystem** [comment]
java.io.FileNotFoundException: /home/projecttl/.minecraft/waypoints (Is a directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at net.minecraft.class_746.handler$zzb000$sendChatMessage(class_746.java:1292)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:376)
	at net.minecraft.class_437.method_25427(class_437.java:369)
	at net.optifine.gui.GuiChatOF.method_25427(GuiChatOF.java:41)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:374)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:703)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22676(class_309.java:702)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:159)
	at net.minecraft.class_1041.method_15998(class_1041.java:454)
	at net.minecraft.class_310.method_1523(class_310.java:1139)
	at net.minecraft.class_310.method_1514(class_310.java:3667)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
